name: weatherapp
description: Weather App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  # Service locator
  get_it: ^4.0.1
  # Value equality
  equatable: ^1.0.1
  # Functional programming thingies
  dartz: ^0.8.9
  # Bloc for state management
  flutter_bloc: ^3.0.0
  # Json generation
  json_annotation: ^3.0.0
  # Remote API
  data_connection_checker: ^0.3.4
  # Retrofit
  retrofit: 1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Json generation
  build_runner: ^1.0.0
  json_serializable: ^3.2.0
  retrofit_generator: 1.3.1

flutter:

  uses-material-design: true